In [1]:
import mlflow

import pandas as pd
from mlflow import MlflowClient
client = MlflowClient(tracking_uri="http://127.0.0.1:5000")

all_experiments = client.search_experiments()

print(all_experiments)

[<Experiment: artifact_location='mlflow-artifacts:/188875176167796080', creation_time=1709065578681, experiment_id='188875176167796080', last_update_time=1709065578681, lifecycle_stage='active', name='model_selection', tags={'mlflow.note.content': 'test mlflow na bazie setu titanic',
 'owner': 'pkwiecien',
 'project_name': 'titanic-mlflow-test'}>, <Experiment: artifact_location='mlflow-artifacts:/147401117630951852', creation_time=1709062861663, experiment_id='147401117630951852', last_update_time=1709062861663, lifecycle_stage='active', name='fe', tags={'mlflow.note.content': 'test mlflow na bazie setu titanic',
 'owner': 'pkwiecien',
 'project_name': 'titanic-mlflow-test'}>, <Experiment: artifact_location='mlflow-artifacts:/661531139765903695', creation_time=1709060170093, experiment_id='661531139765903695', last_update_time=1709060170093, lifecycle_stage='active', name='baseline', tags={'mlflow.note.content': 'test mlflow na bazie setu titanic',
 'owner': 'pkwiecien',
 'project_name': 'titanic-mlflow-test'}>, <Experiment: artifact_location='mlflow-artifacts:/0', creation_time=1709060155998, experiment_id='0', last_update_time=1709060155998, lifecycle_stage='active', name='Default', tags={}>]

In [8]:
summary_data = []

for experiment in all_experiments:
    runs = client.search_runs(experiment_ids=[experiment.experiment_id], filter_string="")
    
    for run in runs:
        experiment_name = experiment.name
        run_name = run.data.tags.get('mlflow.runName', "N/A")  # Adjust based on how you've named your runs
        accuracy_score = run.data.metrics.get('accuracy', None)  # Adjust if using a different metric name
        
        summary_data.append({
            "Experiment Name": experiment_name,
            "Run Name": run_name,
            "Accuracy Score": accuracy_score
        })

summary_df = pd.DataFrame(summary_data)

summary_df.sort_values(by="Accuracy Score", ascending=False)

   Experiment Name     Run Name  Accuracy Score
1  model_selection          XGB        0.841298
5  model_selection          Las        0.839840
3  model_selection      Bagging        0.838491
7  model_selection     Regresja        0.832828
4  model_selection          SVM        0.830031
6  model_selection       Drzewo        0.825815
8               fe        fe_LR        0.821229
0  model_selection          Ada        0.820152
2  model_selection          KNN        0.787905
9         baseline  baseline_LR        0.748252